-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: localhost:3306
-- Üretim Zamanı: 02 Oca 2022, 20:06:00
-- Sunucu sürümü: 10.4.22-MariaDB
-- PHP Sürümü: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `izovi_book`
--
CREATE DATABASE IF NOT EXISTS `izovi_test` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `izovi_test`;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `authors`
--

CREATE TABLE `authors` (
  `author_id` int(11) NOT NULL,
  `first_name` text CHARACTER SET utf8 NOT NULL,
  `last_name` text CHARACTER SET utf8 NOT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `country` text CHARACTER SET utf8 NOT NULL,
  `birth_date` date NOT NULL,
  `author_image_url` text CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `authors`
--

INSERT INTO `authors` (`author_id`, `first_name`, `last_name`, `description`, `country`, `birth_date`, `author_image_url`) VALUES
(1, 'Tana', 'French', 'Tana French, born 1973 in Burlington, Vermont, is an American-Irish writer and theatrical actress. She is a longtime resident of Dublin, Ireland. Her debut novel In the Woods, a psychological mystery, won the Edgar, Anthony, Macavity, and Barry awards for best first novel.', 'USA', '1973-05-10', 'assets/img/author/b1.png'),
(2, 'Rick', 'Riordan', 'Richard Russell Riordan Jr. is an American author. He is known for writing the Percy Jackson & the Olympians series, about a teenager named Percy Jackson who discovers he is a son of the Greek god Poseidon. Riordan\'s books have been translated into forty-two languages and sold more than thirty million copies in the US.', 'USA', '1964-06-05', 'assets/img/author/b2.png'),
(3, 'Suzanne', 'Collins', 'Suzanne Collins was born on August 10, 1962, in Hartford, Connecticut to Jane Brady Collins (born 1932) and Lieutenant Colonel Michael John Collins (1931–2003), a U.S. Air Force officer who served in the Korean War and the Vietnam War.', 'USA', '1962-08-10', 'assets/img/author/b3.png'),
(4, 'J.K.', 'Rowling', 'Joanne Rowling CH, OBE, HonFRSE, FRCPE, FRSL, better known by her pen name J. K. Rowling, is a British author, philanthropist, film producer, and screenwriter. She is author of the Harry Potter fantasy series, which has won multiple awards and sold more than 500 million copies, becoming the best-selling book series in history.', 'England', '1965-07-31', 'assets/img/author/b4.png'),
(5, 'William', 'Shakespeare', 'William Shakespeare was an English playwright, poet and actor, widely regarded as the greatest writer in the English language and the world\'s greatest dramatist. He is often called England\'s national poet and the \"Bard of Avon\" (or simply \"the Bard\"). His extant works, including collaborations, consist of some 39 plays, 154 sonnets, three long narrative poems, and a few other verses, some of uncertain authorship. His plays have been translated into every major living language and are performed more often than those of any other playwright.They also continue to be studied and reinterpreted.', 'England', '1564-04-26', 'assets/img/author/b5.png'),
(6, 'Oscar', 'Wilde', 'Oscar Fingal O\'Flahertie Wills Wilde was an Irish poet and playwright. After writing in different forms throughout the 1880s, he became one of the most popular playwrights in London in the early 1890s. He is best remembered for his epigrams and plays, his novel The Picture of Dorian Gray, and the circumstances of his criminal conviction for gross indecency for consensual homosexual acts in \"one of the first celebrity trials\", imprisonment, and early death from meningitis at age 46.\r\n\r\nWilde\'s parents were Anglo-Irish intellectuals in Dublin. A young Wilde learned to speak fluent French and German. At university, Wilde read Greats; he demonstrated himself to be an exceptional classicist, first at Trinity College Dublin, then at Oxford. He became associated with the emerging philosophy of aestheticism, led by two of his tutors, Walter Pater and John Ruskin. After university, Wilde moved to London into fashionable cultural and social circles.', 'Ireland', '1854-10-16', 'assets/img/author/b6.png'),
(7, 'Ray', 'Bradbury', 'Ray Douglas Bradbury was an American author and screenwriter. One of the most celebrated 20th-century American writers, he worked in a variety of modes, including fantasy, science fiction, horror, mystery, and realistic fiction.', 'USA', '1920-12-22', 'assets/img/author/b7.png'),
(8, 'Antoine de Saint', 'Exupery', 'Antoine Marie Jean-Baptiste Roger, comte de Saint-Exupéry, simply known as de Saint-Exupéry, was a French writer, poet, aristocrat, journalist and pioneering aviator. He became a laureate of several of France\'s highest literary awards and also won the United States National Book Award. He is best remembered for his novella The Little Prince (Le Petit Prince) and for his lyrical aviation writings, including Wind, Sand and Stars and Night Flight.', 'France', '1900-06-29', 'assets/img/author/b8.png'),
(9, 'Arthur', 'Golden', 'Golden was born in Chattanooga, Tennessee, the son of Ruth (née Sulzberger) and Ben Hale Golden. His mother was Jewish and his father a gentile. Through his mother he is a member of the Ochs-Sulzberger family. His mother was a daughter of long-time Times publisher Arthur Hays Sulzberger and granddaughter of Times owner and publisher Adolph Ochs. His parents divorced when he was eight years old. His father died five years after. He was raised in Lookout Mountain, Georgia and attended Lookout Mountain Elementary School in Lookout Mountain, Tennessee.', 'USA', '1956-12-06', 'assets/img/author/b9.png'),
(10, 'Harper', 'Lee', 'Nelle Harper Lee was an American novelist best known for her 1960 novel To Kill a Mockingbird. It won the 1961 Pulitzer Prize and has become a classic of modern American literature. Lee has received numerous accolades and honorary degrees, including the Presidential Medal of Freedom in 2007 which was awarded for her contribution to literature. She assisted her close friend Truman Capote in his research for the book In Cold Blood (1966). Capote was the basis for the character Dill Harris in To Kill a Mockingbird.', 'USA', '1928-04-28', 'assets/img/author/b10.png'),
(11, 'Jane', 'Austen', 'Jane Austen was an English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century. Austen\'s plots often explore the dependence of women on marriage in the pursuit of favourable social standing and economic security. Her works critique the novels of sensibility of the second half of the 18th century and are part of the transition to 19th-century literary realism. Her use of biting irony, along with her realism, humour, and social commentary, have long earned her acclaim among critics, scholars, and popular audiences alike.', 'England', '1775-12-16', 'assets/img/author/b11.png'),
(12, 'Markus', 'Zusak', 'Zusak was born in Sydney, Australia. His mother Lisa is originally from Germany and his father Joseph is from Austria. They emigrated to Australia in the late 1950s. Markus is the youngest of four children and has two sisters and one brother. He attended Engadine High School and briefly returned there to teach English while writing. He studied English and history at the University of New South Wales, from which he graduated with a Bachelor of Arts and a Diploma of Education.', 'Australia', '1975-06-23', 'assets/img/author/b12.png'),
(13, 'George', 'Orwell', 'Eric Arthur Blair known by his pen name George Orwell, was an English novelist, essayist, journalist and critic. His work is characterised by lucid prose, biting social criticism, total opposition to totalitarianism, and outspoken support of democratic socialism.', 'England', '1903-06-25', 'assets/img/author/b13.png'),
(14, 'C.S', 'Lewis', 'Clive Staples Lewis  was a British writer and lay theologian. He held academic positions in English literature at both Oxford University (Magdalen College, 1925–1954) and Cambridge University (Magdalene College, 1954–1963). He is best known for his works of fiction, especially The Screwtape Letters, The Chronicles of Narnia, and The Space Trilogy, and for his non-fiction Christian apologetics, such as Mere Christianity, Miracles, and The Problem of Pain.', 'England', '1898-11-28', 'assets/img/author/b14.png'),
(15, 'John', 'Green', 'John Michael Green is an American author, YouTube content creator, and podcaster. He won the 2006 Printz Award for his debut novel, Looking for Alaska, and has had several of his subsequent books debut at number one on The New York Times Best Seller list, including his most popular novel, The Fault in Our Stars. The 2014 film adaptation of The Fault in Our Stars opened at number one at the box office and was a commercial and critical success. In 2014, Green was included in Time magazine\'s list of The 100 Most Influential People in the World. Another film based on a Green novel, Paper Towns, was released on July 24, 2015.', 'USA', '1977-08-24', 'assets/img/author/b15.png'),
(16, 'Shel', 'Silverstein', 'Sheldon Allan Silverstein was an American writer, poet, cartoonist, songwriter, and playwright. He was best known for his cartoons, songs, and children\'s books. He styled himself as Uncle Shelby in some works. His books have been translated into more than 30 languages and have sold more than 20 million copies. His songs have been recorded and popularized by a wide range of acts including Johnny Cash, The Irish Rovers, and Dr. Hook & the Medicine Show. He was the recipient of two Grammy Awards as well as Golden Globe Award and Academy Award nominations.', 'USA', '1930-09-25', 'assets/img/author/b16.png'),
(17, 'Albert', 'Camus', 'Albert Camus was a French philosopher, author, and journalist. He was awarded the 1957 Nobel Prize in Literature at the age of 44, the second-youngest recipient in history. His works include The Stranger, The Plague, The Myth of Sisyphus, The Fall, and The Rebel.\r\n\r\nCamus was born in French Algeria to Pieds Noirs parents. He spent his childhood in a poor neighbourhood and later studied philosophy at the University of Algiers. He was in Paris when the Germans invaded France during World War II in 1940. Camus tried to flee but finally joined the French Resistance where he served as editor-in-chief at Combat, an outlawed newspaper. After the war, he was a celebrity figure and gave many lectures around the world. He married twice but had many extramarital affairs. Camus was politically active; he was part of the left that opposed the Soviet Union because of its totalitarianism. Camus was a moralist and leaned towards anarcho-syndicalism. He was part of many organisations seeking European integration. During the Algerian War (1954–1962), he kept a neutral stance, advocating for a multicultural and pluralistic Algeria, a position that caused controversy and was rejected by most parties.', 'France', '1913-11-07', 'assets/img/author/b17.png'),
(18, 'Gabriel Garcia ', 'Marquez', 'Gabriel García Márquez was a Colombian novelist, short-story writer, screenwriter, and journalist, known affectionately as Gabo or Gabito throughout Latin America. Considered one of the most significant authors of the 20th century, particularly in the Spanish language, he was awarded the 1972 Neustadt International Prize for Literature and the 1982 Nobel Prize in Literature. He pursued a self-directed education that resulted in leaving law school for a career in journalism. From early on he showed no inhibitions in his criticism of Colombian and foreign politics. In 1958 he married Mercedes Barcha Pardo (d. 2020, aged 87); they had two sons, Rodrigo and Gonzalo.\r\n\r\nGarcía Márquez started as a journalist and wrote many acclaimed non-fiction works and short stories, but is best known for his novels, such as One Hundred Years of Solitude (1967), Chronicle of a Death Foretold (1981), and Love in the Time of Cholera (1985). His works have achieved significant critical acclaim and widespread commercial success, most notably for popularizing a literary style known as magic realism, which uses magical elements and events in otherwise ordinary and realistic situations. Some of his works are set in the fictional village of Macondo (mainly inspired by his birthplace, Aracataca), and most of them explore the theme of solitude.', 'Colombia', '1927-03-06', 'assets/img/author/b18.png'),
(19, 'Orhan', 'Pamuk', 'Ferit Orhan Pamuk is a Turkish novelist, screenwriter, academic and recipient of the 2006 Nobel Prize in Literature. One of Turkey\'s most prominent novelists, his work has sold over thirteen million books in sixty-three languages, making him the country\'s best-selling writer.\r\n\r\nPamuk is the author of novels including Silent House, The White Castle, The Black Book, The New Life, My Name Is Red, Snow, The Museum of Innocence, A Strangeness in My Mind and The Red-Haired Woman. He is the Robert Yik-Fong Tam Professor in the Humanities at Columbia University, where he teaches writing and comparative literature. He was elected to the American Philosophical Society in 2018.\r\n\r\nOf partial Circassian descent and born in Istanbul, Pamuk is the first Turkish Nobel laureate. He is also the recipient of numerous other literary awards. My Name Is Red won the 2002 Prix du Meilleur Livre Étranger, 2002 Premio Grinzane Cavour and 2003 International Dublin Literary Award.\r\n\r\nThe European Writers\' Parliament came about as a result of a joint proposal by Pamuk and José Saramago. Pamuk\'s willingness to write books about contentious historical and political events put him at risk of censure in his homeland. In 2005, an ultra-nationalist lawyer sued him over a statement regarding the Armenian genocide in the Ottoman Empire. His intention, according to Pamuk himself, had been to highlight issues relating to freedom of speech in the country of his birth. The court initially declined to hear the case, but in 2011 Pamuk was ordered to pay 6,000 liras in total compensation for having insulted the plaintiffs\' honor.', 'Turkey', '1952-06-07', 'assets/img/author/b19.png'),
(20, 'Eric', 'Carle', 'Eric Carle was an American author, designer and illustrator of children\'s books. His picture book The Very Hungry Caterpillar, first published in 1969, has been translated into more than 66 languages and sold more than 50 million copies. His career as an illustrator and children\'s book author took off after he collaborated on Brown Bear, Brown Bear, What Do You See?. He illustrated more than 70 books, most of which he also wrote, and more than 145 million copies of his books have been sold around the world.\r\n\r\nIn 2003, the American Library Association awarded Carle the biennial Laura Ingalls Wilder Medal (now called the Children\'s Literature Legacy Award), a prize for writers or illustrators of children\'s books published in the U.S. who have made lasting contributions to the field. Carle was also a U.S. nominee for the biennial, international Hans Christian Andersen Award in 2010.', 'USA', '1929-06-25', 'assets/img/author/b20.png'),
(21, 'Theodor Seuss', 'Geisel', 'Theodor Seuss Geisel was an American children\'s author, political cartoonist, illustrator, poet, animator, and filmmaker. He is known for his work writing and illustrating more than 60 books under the pen name Dr. Seuss. His work includes many of the most popular children\'s books of all time, selling over 600 million copies and being translated into more than 20 languages by the time of his death.', 'USA', '1902-03-02', 'assets/img/author/b21.png'),
(22, 'Chris', 'Van Allsburg', 'Chris Van Allsburg is an American illustrator and writer of children\'s books. He has won two Caldecott Medals for U.S. picture book illustration, for Jumanji (1981) and The Polar Express (1985), both of which he also wrote; both were later adapted as successful motion pictures. He was also a Caldecott runner-up in 1980 for The Garden of Abdul Gasazi. For his contribution as a children\'s illustrator, he was a 1986 U.S. nominee for the biennial International Hans Christian Andersen Award, the highest international recognition for creators of children\'s books. He received the honorary degree of Doctor of Humane Letters from the University of Michigan in April 2012.', 'USA', '1949-06-18', 'assets/img/author/b22.png'),
(23, 'Roald', 'Dahl', 'Roald Dahl was a British novelist, short-story writer, poet, screenwriter, and wartime fighter pilot. His books have sold more than 250 million copies worldwide.\r\n\r\nDahl was born in Wales to affluent Norwegian immigrant parents, and spent most of his life in England. He served in the Royal Air Force (RAF) during the Second World War. He became a fighter pilot and, subsequently, an intelligence officer, rising to the rank of acting wing commander. He rose to prominence as a writer in the 1940s with works for children and for adults, and he became one of the world\'s best-selling authors. He has been referred to as \"one of the greatest storytellers for children of the 20th century\". His awards for contribution to literature include the 1983 World Fantasy Award for Life Achievement and the British Book Awards\' Children\'s Author of the Year in 1990. Though he and his work have been criticised for antisemitism, racism and misogyny, in 2008, The Times placed Dahl 16th on its list of \"The 50 Greatest British Writers Since 1945\".\r\n\r\nDahl\'s short stories are known for their unexpected endings, and his children\'s books for their unsentimental, macabre, often darkly comic mood, featuring villainous adult enemies of the child characters. His children\'s books champion the kindhearted and feature an underlying warm sentiment. His works for children include James and the Giant Peach, Charlie and the Chocolate Factory, Matilda, The Witches, Fantastic Mr Fox, The BFG, The Twits, The Giraffe and the Pelly and Me and George\'s Marvellous Medicine. His adult works include Tales of the Unexpected.', 'England', '1916-10-13', 'assets/img/author/b23.png');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `books`
--

CREATE TABLE `books` (
  `book_id` int(11) NOT NULL,
  `title` text CHARACTER SET utf8 NOT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `author` text CHARACTER SET utf8 NOT NULL,
  `author_id` int(11) DEFAULT NULL,
  `publisher` text CHARACTER SET utf8 NOT NULL,
  `year` year(4) NOT NULL,
  `rating` float NOT NULL,
  `total_pages` int(11) NOT NULL,
  `category` text CHARACTER SET utf8 NOT NULL,
  `isbn` text CHARACTER SET utf8 NOT NULL,
  `language` text CHARACTER SET utf8 NOT NULL,
  `image_url` text CHARACTER SET utf8 NOT NULL,
  `pdf_url` text CHARACTER SET utf8 DEFAULT NULL,
  `mp3_url` text CHARACTER SET utf8 DEFAULT NULL,
  `review` text DEFAULT NULL,
  `audio` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `books`
--

INSERT INTO `books` (`book_id`, `title`, `description`, `author`, `author_id`, `publisher`, `year`, `rating`, `total_pages`, `category`, `isbn`, `language`, `image_url`, `pdf_url`, `mp3_url`, `review`, `audio`) VALUES
(1, 'Harry Potter and the Deathly Hallows', 'It\'s no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it\'s up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry\'s Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death.', 'J.K. Rowling', 4, 'Arthur A. Levine Books', 2007, 4.85, 759, 'Fantasy', '0545010225', 'English', 'assets/img/cover/deathly.jpg', NULL, NULL, 'This last Harry Potter series\' book recount the story of Harry and his final stand with Voldemort.\n\nThis book was very enjoyable. The end was satisfying even if it was sad. I loved all the characters, especially how Draco Malfoy changed throughout the series. I was sad when some of my favourite characters died, but it kept me wondering what would happen next. Little details became big ones and the end explained everything. This wrapped up the Harry Potter series very nicely.', 'Yes'),
(2, 'Mockingjay', 'Katniss Everdeen, girl on fire, has survived, even though her home has been destroyed. Gale has escaped. Katniss\'s family is safe. Peeta has been captured by the Capitol. District 13 really does exist. There are rebels. There are new leaders. A revolution is unfolding.\r\n\r\nIt is by design that Katniss was rescued from the arena in the cruel and haunting Quarter Quell, and it is by design that she has long been part of the revolution without knowing it. District 13 has come out of the shadows and is plotting to overthrow the Capitol. Everyone, it seems, has had a hand in the carefully laid plans—except Katniss.\r\n\r\nThe success of the rebellion hinges on Katniss\'s willingness to be a pawn, to accept responsibility for countless lives, and to change the course of the future of Panem. To do this, she must put aside her feelings of anger and distrust. She must become the rebels\' Mockingjay—no matter what the personal cost.', 'Suzanne Collins', 3, 'Scholastic Press', 2010, 4.15, 398, 'Dystopian', '0545663261', 'English', 'assets/img/cover/mocking.jpg', NULL, NULL, 'This book is really incredible. I had heard about it, the sad moments of it, and even when there were very sad parts, i didn\'t cry once during it. The writing was truly a piece of art, i had trouble letting the book down. One of my favorites, just like \'Hunger games\' and \'Catching fire\' The trilogy is amazing :)', 'Yes'),
(3, 'The Battle of the Labyrinth', 'Percy Jackson isn\'t expecting freshman orientation to be any fun. But when a mysterious mortal acquaintance appears at his potential new school, followed by demon cheerleaders, things quickly move from bad to worse.\r\n\r\nIn this fourth installment of the blockbuster series, time is running out as war between the Olympians and the evil Titan lord Kronos draws near. Even the safe haven of Camp Half-Blood grows more vulnerable by the minute as Kronos\'s army prepares to invade its once impenetrable borders. To stop the invasion, Percy and his demigod friends must set out on a quest through the Labyrinth - a sprawling underground world with stunning surprises at every turn.', 'Rick Riordan', 2, 'Hyperion Books', 2008, 3.92, 361, 'Fantasy', '1423101499', 'English', 'assets/img/cover/2120932.jpg', NULL, NULL, 'This book is about three people who go into the ancient Labyrinth. They are trying to find the centre of the Labyrinth where Daedulus works, because they want to talk to him about how to navigate through the Labyrinth. They need to do this to stop their evil enemies (Luke, Kronos and their army of monsters) from finding Ariadne’s string and navigating through the Labyrinth to destroy Camp Half Blood and then Olympus.', 'Yes'),
(5, 'Fahrenheit 451', 'Sixty years after its original publication, Ray Bradbury’s internationally acclaimed novel Fahrenheit 451 stands as a classic of world literature set in a bleak, dystopian future. Today its message has grown more relevant than ever before.\r\n\r\nGuy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.', 'Ray Bradbury', 7, 'Simon & Schuster', 1953, 4.72, 194, 'Dystopian', '1451673264', 'English', 'assets/img/cover/451.jpg', NULL, NULL, 'People are discouraging this book by saying that it is not good or in appropriate for their child but in all honesty this book could be like the future if kids don\'t pick up a book at all. Fahrenheit 451 is an outstanding book and i recommend it to all my friends and their siblings because it shows how a book can be the downfall and the worlds savior. but most importantly its about how the future is effected by what people see as unfair or not equal. with 4 out of 5 stars Fahrenheit 451 is my go to pick up book that i cant stop reading', 'Yes'),
(6, 'Romeo and Juliet', 'In Romeo and Juliet, Shakespeare creates a violent world, in which two young people fall in love. It is not simply that their families disapprove; the Montagues and the Capulets are engaged in a blood feud.\r\n\r\nIn this death-filled setting, the movement from love at first sight to the lovers’ final union in death seems almost inevitable. And yet, this play set in an extraordinary world has become the quintessential story of young love. In part because of its exquisite language, it is easy to respond as if it were about all young lovers.', 'William Shakespeare', 5, 'Folger Shakespeare Library', 2002, 4.56, 281, 'Romance', '0743477111', 'English', 'assets/img/cover/romeo.jpg', NULL, NULL, 'One of Shakespeare’s most well known plays is Romeo and Juliet. This play is about two star-cross’d lovers; two families at war, the daughter of one loves the son of another, and it ends in a tragic ending. We see the journey of the hate between the two families, but also the secret love that goes on behind the two lovers. I feel like this play is overrated. Everyone talks about this book and I thought it would be good, but I didn’t enjoy it as much as I thought. I preferred some of Shakespeare’s other plays, like Hamlet. It was a good story, however, it was hard to read because it is written in an old English language. I didn’t enjoy the ending because it wasn’t fair. However, it was a unique story that is different from other books I have read, and it was a cool experience reading a play instead of an actual book. The old version of the movie is also fun to watch, if you feel like reading the book is too hard. Overall, Romeo and Juliet is a popular play that everyone talks about, however, I would recommend Hamlet over this book, though it was still a special experience reading this play.', 'Yes'),
(7, 'The Little Prince', 'A pilot stranded in the desert awakes one morning to see, standing before him, the most extraordinary little fellow. \"Please,\" asks the stranger, \"draw me a sheep.\" And the pilot realizes that when life\'s events are too difficult to understand, there is no choice but to succumb to their mysteries. He pulls out pencil and paper... And thus begins this wise and enchanting fable that, in teaching the secret of what is really important in life, has changed forever the world for its readers.\r\n\r\nFew stories are as widely read and as universally cherished by children and adults alike as The Little Prince, presented here in a stunning new translation with carefully restored artwork. The definitive edition of a worldwide classic, it will capture the hearts of readers of all ages.', 'Antoine de Saint-Exupery', 8, 'Harcourt', 2000, 4.11, 96, 'Childrens', '1607963027', 'French', 'assets/img/cover/prince.jpg', NULL, NULL, 'Written by the French aristocrat, writer, and military adviser Antoine de Saint-Exupéry, The Little Prince depicts the life of an imaginary “prince” living on a small asteroid named B 612. The novel starts with the narrator crashing in the Sahara Desert, with a water supply only adequate to last 8 days. In this desert, the man meets the prince, who thus speaks of his background and life story. On his asteroid, the prince focuses on a rose, in which he fell in love with. This relationship between the prince and the rose ends when the prince decides that the rose is taking advantage of him, and hence decides to explore the rest of the universe. The Little Prince reflects on many modern day topics, such as the loss of creativity and imagination through aging. Underneath the humorous and entertaining story, The Little Prince ponders and questions societal standards for adults. Thus, I would recommend this book to ages 10+.', 'Yes'),
(8, 'Memoirs of a Geisha', 'A literary sensation and runaway bestseller, this brilliant debut novel presents with seamless authenticity and exquisite lyricism the true confessions of one of Japan\'s most celebrated geisha.\r\n\r\nIn Memoirs of a Geisha, we enter a world where appearances are paramount; where a girl\'s virginity is auctioned to the highest bidder; where women are trained to beguile the most powerful men; and where love is scorned as illusion. It is a unique and triumphant work of fiction - at once romantic, erotic, suspenseful - and completely unforgettable.', 'Arthur Golden', 9, 'Vintage International', 2005, 3.97, 503, 'Fiction', '0679781587', 'English', 'assets/img/cover/geisha.jpg', NULL, NULL, 'I have read this wonderful book several times. If you have seen the movie be sure to read the book, it is so much more than the movie.\n\nThe author draws you into a world so different than ours from the very first sentence and I recommend it to anyone wanting to escape our Western world and discover a place where customs are so different from ours.\n\nThe story is written as if it were nonfiction. The story is told through a geisha (Sayuri) and is transcribed by a friend and published after her death.\n\nThe book basically presents the life story of one geisha who through often very harsh events in her life transforms herself from a fisherman’s daughter into one of the most famous geishas of Japan. She is put into a Geisha house which demand very strict discipline and service and has hierarchies that abuse power. Once she reaches her goal, stability of her career is unclear as many events threaten to destroy it as they have for other geishas who are often dragged into lives of prostitution. WWII presents other unexpected challenges she has to face.\n\nThis is a enjoyable book about determination within boundaries.', 'No'),
(9, 'The Hunger Games', 'In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.\r\n\r\nSixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister\'s place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.', 'Suzanne Collins', 3, 'Scholastic Press', 2008, 4.18, 374, 'Dystopian', '0439023521', 'English', 'assets/img/cover/hunger.jpg', NULL, NULL, 'I loved this book, I really like Catness as a strong female character. It had me one the end he of my seat waiting to find out what was going to happen next.', 'Yes'),
(10, 'Harry Potter and the Order of the Phoenix', 'There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?\r\n\r\nHarry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.\r\n\r\nAs the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.\r\n\r\nHis fate depends on them all.', 'J.K. Rowling', 4, 'Scholastic Press', 2004, 4.65, 870, 'Fantasy', '0439358078', 'English', 'assets/img/cover/2.jpg', NULL, NULL, 'The 5th Pivotal book to the HP series is the longest -- over 800 pages long! I felt like this book was fine to read; once you read this book over and over, it loses some of its fun magic moments. This book is less intense than the 4th book, but it does have its share of action/violence. Let\'s say you meet one the infamous teacher: Dolores Umbridge. She makes the book very interesting and -- do I dare say it? -- even fun at some points to read about. The message in this book is clear and straight forward: good can conquer evil. The action/violence involves some tourting, magical fights, injuries, etc. Plenty of people in this book gets injured in some way. I have to say, this book is too long and it\'s kind of hard to read when Harry\'s temper gets the best of him (in like every chapter); but no denying, this book is as fun as the others and a must-read if you are HP Fan!', 'Yes'),
(11, 'To Kill a Mockingbird', 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. \"To Kill A Mockingbird\" became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.\r\n\r\nCompassionate, dramatic, and deeply moving, \"To Kill A Mockingbird\" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.', 'Harper Lee', 10, 'Harper Perennial', 2006, 4.23, 336, 'Classics', '0060935464', 'English', 'assets/img/cover/2657.jpg', NULL, NULL, 'To Kill a Mockingbird is full of life lessons. Atticus is pretty much the perfect human and the wisdom he imparts to Scout and Jem is profound. I liked how Harper Lee took her time building up to the actual trial. She shows us years of life in Maycomb so that the reader can truly understand the South in the 1930s. There is a rich cast of supporting characters, all vividly drawn. It’s tragic to realize that not all that much has changed in how our country treats black people since the time of this book. Black people are still treated unfairly by the criminal justice system quite often, resulting in America’s huge mass incarceration problem.', 'No'),
(12, 'Pride and Prejudice', 'Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work \"her own darling child\" and its vivacious heroine, Elizabeth Bennet, \"as delightful a creature as ever appeared in print.\" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen\'s radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.', 'Jane Austen', 11, 'Modern Library', 2000, 3.75, 279, 'Romance', '0141439513', 'English', 'assets/img/cover/1885.jpg', NULL, NULL, 'I think the plot is very witty and amusing, and it is an interesting insight into what women’s life was like at the time. Equally, I love the wonderful and spirited Lizzie Bennett, with her wit and humour. Also, I like the way the Bennett’s are portrayed, and the way Mrs Bennett is obsessed with marrying the daughters off, and how Mr Bennett and the daughters put up with it. I also like the way Jane Austen makes fun of people. She pokes fun at Lady Catherine, who is Mr Darcy’s aunt, and she ridicules the upper class all the time.', 'Yes'),
(13, 'The Book Thief', 'It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will be busier still.\r\n\r\nBy her brother\'s graveside, Liesel\'s life is changed when she picks up a single object, partially hidden in the snow. It is The Gravedigger\'s Handbook, left behind there by accident, and it is her first act of book thievery. So begins a love affair with books and words, as Liesel, with the help of her accordian-playing foster father, learns to read. Soon she is stealing books from Nazi book-burnings, the mayor\'s wife\'s library, wherever there are books to be found.\r\n\r\nBut these are dangerous times. When Liesel\'s foster family hides a Jew in their basement, Liesel\'s world is both opened up, and closed down.\r\n\r\nIn superbly crafted writing that burns with intensity, award-winning author Markus Zusak has given us one of the most enduring stories of our time.', 'Markus Zusak', 12, 'Alfred A. Knopf', 2006, 3.23, 552, 'Historical', '0375842209', 'English', 'assets/img/cover/19063._SY475_.jpg', NULL, NULL, 'Combined with historical background knowledge about Nazi Germany, it shows how the war impacted on the folk. The idea of using death as the narrator is genius and the style of writing gives a lot of space for interpretation. It also emphasizes the impact of books and words and their might,', 'Yes'),
(14, 'Animal Farm', 'A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.\r\nWhen Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh.', 'George Orwell', 13, 'Signet Classics', 1996, 4.89, 141, 'Dystopian', '1946963445', 'English', 'assets/img/cover/170448.jpg', NULL, NULL, 'Animal Farm is a satirical novel that mimicked the start and life of communism. The farmers represent the old government while the pigs represent the new age communist leaders. The rest of the animals on the farm represent the working class and would be the people that will be soon taken advantage of. Animal Farm has many themes throughout the novel about the influence that leaders can have on their population. This theme is shown when the pigs start to take advantage of the rest of the animals by spreading fake news or propaganda that soon portrays them as noble leaders. This can happen due to the lack of education of many of the animals and when some of the Animals try to speak up they are often criticized and sometimes killed. Animal Farm is a great novel that allows the readers to understand the influence that a government interestingly has on its people with many themes. Animal Farm is a great book that anyone can sit down and analyze due to the main small details that can be missed but represent major themes in the book. One of the negative things about the book is that in some chapters, the plot starts to slow down and the reader can often get bored and then the pace will suddenly pick up which may surprise the reader. Overall Animal Farm is a classic book that has many overarching themes about influence and the importance of education.', 'Yes'),
(15, 'The Chronicles of Narnia', 'Journeys to the end of the world, fantastic creatures, and epic battles between good and evil—what more could any reader ask for in one book? The book that has it all is The Lion, the Witch and the Wardrobe, written in 1949 by Clive Staples Lewis. But Lewis did not stop there. Six more books followed, and together they became known as The Chronicles of Narnia.\r\n\r\nFor the past fifty years, The Chronicles of Narnia have transcended the fantasy genre to become part of the canon of classic literature. Each of the seven books is a masterpiece, drawing the reader into a land where magic meets reality, and the result is a fictional world whose scope has fascinated generations.\r\n\r\nThis edition presents all seven books—unabridged—in one impressive volume. The books are presented here in chronlogical order, each chapter graced with an illustration by the original artist, Pauline Baynes. Deceptively simple and direct, The Chronicles of Narnia continue to captivate fans with adventures, characters, and truths that speak to readers of all ages, even fifty years after they were first published.', 'C.S. Lewis', 14, 'Harper Perennial', 1956, 3.52, 767, 'Fantasy', '0060598247', 'English', 'assets/img/cover/narnia.jpg', NULL, NULL, 'Welcome to Narnia!\nA country filled with talking creatures centaurs and more!\nThis book truly shows that darkness is merely a reflection of light!\nA wonderful series for all ages.\n\nMy favourite part of the series was the ending when everything became perfect\nC.S Lewis (the author) was actually a christian and if you look closely you can see how much it relates to our world!', 'No'),
(16, 'The Fault in Our Stars', 'Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel\'s story is about to be completely rewritten.\r\n\r\nInsightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning author John Green\'s most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love. ', 'John Green', 15, 'Dutton Books', 2012, 2.94, 313, 'Romance', '014242417X', 'English', 'assets/img/cover/11870085.jpg', NULL, NULL, 'One doesn’t like to throw around phrases like “instant classic” lightly, but I can see The Fault in Our Stars taking its place alongside Are You There God? It’s Me, Margaret in the young-adult canon. Green’s book is also a good example of why so many adult readers are turning to young-adult literature for the pleasures and consolations they used to get from conventional literary fiction.', 'Yes'),
(17, 'The Giving Tree', 'So begins a story of unforgettable perception, beautifully written and illustrated by the gifted and versatile Shel Silverstein.\r\n\r\nEvery day the boy would come to the tree to eat her apples, swing from her branches, or slide down her trunk...and the tree was happy. But as the boy grew older he began to want more from the tree, and the tree gave and gave and gave.\r\n\r\nThis is a tender story, touched with sadness, aglow with consolation. Shel Silverstein has created a moving parable for readers of all ages that offers an affecting interpretation of the gift of giving and a serene acceptance of another\'s capacity to love in return.', 'Shel Silverstein', 16, 'Harper Perennial', 1964, 4.36, 64, 'Childrens', '0060256664', 'English', 'assets/img/cover/giving.jpg', NULL, NULL, 'Shel Silverstein created a connection within this story and gave out a very powerful message for young readers, it is better to give than receive. Overall, I would like to recommend this book to not just children, but everyone.\n\nThe Giving Tree will truly inspire you to be good and do good. Life is a beautiful gift, appreciate it.', 'Yes'),
(18, 'The Picture of Dorian Gray', 'Written in his distinctively dazzling manner, Oscar Wilde’s story of a fashionable young man who sells his soul for eternal youth and beauty is the author’s most popular work. The tale of Dorian Gray’s moral disintegration caused a scandal when it ﬁrst appeared in 1890, but though Wilde was attacked for the novel’s corrupting inﬂuence, he responded that there is, in fact, “a terrible moral in Dorian Gray.” Just a few years later, the book and the aesthetic/moral dilemma it presented became issues in the trials occasioned by Wilde’s homosexual liaisons, which resulted in his imprisonment. Of Dorian Gray’s relationship to autobiography, Wilde noted in a letter, “Basil Hallward is what I think I am: Lord Henry what the world thinks me: Dorian what I would like to be—in other ages, perhaps.', 'Oscar Wilde', 6, 'Random House', 1980, 4.69, 272, 'Classics', '1936041227', 'English', 'assets/img/cover/thepictureof.jpg', NULL, NULL, 'The character of Dorian Gray believable and likeable because he had two personalities and this made him really interesting. The plot was fabulous because there was a murder and action. The author’s style is great, clear and it has got a fantastic aura. I think the author did a good job and I wouldn’t do anything differently.', 'Yes'),
(19, 'The Tales of Beedle the Bard', 'The Tales of Beedle the Bard contains five richly diverse fairy tales, each with its own magical character, that will variously bring delight, laughter and the thrill of mortal peril.\r\n\r\nAdditional notes for each story penned by Professor Albus Dumbledore will be enjoyed by Muggles and wizards alike, as the Professor muses on the morals illuminated by the tales, and reveals snippets of information about life at Hogwarts.\r\n\r\nA uniquely magical volume, with illustrations by the author, J. K. Rowling, that will be treasured for years to come', 'J.K. Rowling', 4, 'Bloomsbury', 2008, 4.09, 109, 'Fantasy', '1338125680', 'English', 'assets/img/cover/thetales.jpg', NULL, NULL, 'The book is perfectly charming and short enough to read in one sitting, however, do not be surprised if like me you find yourself turning the first page yet again as soon as you have finished reading the last.', 'No'),
(20, '1984', 'Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell\'s nightmarish vision of a totalitarian, bureaucratic world and one poor stiff\'s attempt to find individuality. The brilliance of the novel is Orwell\'s prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.', 'George Orwell', 13, 'Houghton Mifflin', 1949, 4.79, 298, 'Dystopian', '6257287405', 'English', 'assets/img/cover/1984.jpg', NULL, NULL, 'Every once in awhile, a book comes along that you can’t put down. Sometimes it even scares you, gets you thinking, and warps your mind.', 'Yes'),
(21, 'Down and Out in Paris and London', 'This unusual fictional memoir - in good part autobiographical - narrates without self-pity and often with humor the adventures of a penniless British writer among the down-and-outs of two great cities. The Parisian episode is fascinating for its expose of the kitchens of posh French restaurants, where the narrator works at the bottom of the culinary echelon as dishwasher, or plongeur. In London, while waiting for a job, he experiences the world of tramps, street people, and free lodging houses. In the tales of both cities we learn some sobering Orwellian truths about poverty and of society. ', 'George Orwell', 13, 'Mariner Books', 1972, 4.05, 213, 'Nonfiction', '8194628695', 'English', 'assets/img/cover/down.jpg', NULL, NULL, 'This book falls into two distinct parts, both with an underlying common theme, the revealing of poverty at close range. Not an appealing subject, you will say. But have a look at the book and catch the strange fascination of the telling.', 'No'),
(23, 'Homage to Catalonia', 'In 1936 George Orwell travelled to Spain to report on the Civil War and instead joined the fight against the Fascists. This famous account describes the war and Orwell’s own experiences. Introduction by Lionel Trilling.', 'George Orwell', 13, 'Harcourt', 1938, 4.06, 232, 'Historical', '1618952730', 'English', 'assets/img/cover/home.jpg', NULL, NULL, 'This is just a wonderful book. Like all of Orwell’s work it’s incredibly well written. It’s a very powerful piece of prose. Usually this book is seen as a picturesque account of an ultimately failed attempt to fight fascism, but what made a big impression on me was the fact that people like Orwell and 30,000 other foreign volunteers went to fight fascism in Spain at all. It’s in such contrast to the way we think politics works now.', 'No'),
(24, 'Burmese Days', 'Set in the days of the Empire, with the British ruling in Burma, Orwell\'s book describes corruption and imperial bigotry. Flory, a white timber merchant, befriends Dr Veraswami, a black enthusiast for the Empire, whose downfall can only be prevented by membership at an all-white club.', 'George Orwell', 13, '1st World Library', 1934, 3.87, 276, 'Fiction', '9176379043', 'English', 'assets/img/cover/burmese.jpg', NULL, NULL, 'This is a brilliant and insightful story centered on the nature of racism and colonialism in Burma (now Myanmar) in the timeframe after World War I. Orwell spent considerable time in that country so he has a good understanding of the society he is describing. He also has a great deal to say about the subculture of the British colonists in Burma, and he portrays that subculture as highly insulated and at times nearly suffocating and it’s conformity and judgementalism.', 'Yes'),
(25, 'The Importance of Being Earnest', 'The Complete Works of Oscar Wilde contains his only novel, The Picture of Dorian Gray; all his stories, plays and poems; and a substantial number of his essays and letters, all in their most authoritative texts. The Importance of Being Earnest, for example, is given in the original four-act version, with readings from the revised edition, while \"De Profundis,\" his moving and tragic letter to Lord Alfred Douglas, is from the manuscript held by the British Museum until 1960 -- the only complete and accurate source.\n\nThis is the first one-volume anthology to include \"The Portrait of Mr. W.H.,\" in which Wilde expanded his theory concerning the mystery of Shakespeare\'s sonnets, and also \"A Few Maxims for the Instruction of the Over-Educated,\" a series of aphorisms typical of Wilde. It carried, too, an introduction by Vyvyan Holland, Oscar Wilde\'s son.', 'Oscar Wilde', 6, 'Harper Perennial', 1920, 4.15, 76, 'Classics', '1595401148', 'English', 'assets/img/cover/theimportance.jpg', NULL, NULL, 'This play is rather short and I managed to read the entire play in about an hour. There are very few stage directions in The Importance of Being Earnest, but this play is all about what people are saying, rather than what they are doing. Everything the characters say is either nonsense or completely backwards which is very funny for the reader.', 'No'),
(26, 'An Ideal Husband', 'Although Oscar Wilde (1854–1900) created a wide range of poetry, essays, and fairy tales (and one novel) in his brief, tragic life, he is perhaps best known as a dramatist. His witty, clever drama, populated by brilliant talkers skilled in the art of riposte and paradox, are still staples of the theatrical repertoire.\r\nAn Ideal Husband revolves around a blackmail scheme that forces a married couple to reexamine their moral standards — providing, along the way, a wry commentary on the rarity of politicians who can claim to be ethically pure. A supporting cast of young lovers, society matrons, an overbearing father, and a formidable femme fatale continually exchange sparkling repartee, keeping the play moving at a lively pace.\r\nLike most of Wilde\'s plays, this scintillating drawing-room comedy is wise, well-constructed, and deeply satisfying. An instant success at its 1895 debut, the play continues to delight audiences over one hundred years later. An Ideal Husband is a must-read for Wilde fans, students of English literature, and anyone delighted by wit, urbanity, and timeless sophistication.', 'Oscar Wilde', 6, 'Dover Publications', 1920, 4.01, 83, 'Classics', '1954525532', 'English', 'assets/img/cover/an.jpg', NULL, NULL, 'A dazzling blend of farce and morality, this play explores human frailty and social hypocrisy. Sir Robert Chiltern’s secret is discovered and exposed. He is accused of having exploited government secrets for his own gain early in his political career.', 'No'),
(27, 'The Canterville Ghost', 'This is Oscar Wilde\'s tale of the American family moved into a British mansion, Canterville Chase, much to the annoyance of its tired ghost. The family -- which refuses to believe in him -- is in Wilde\'s way a commentary on the British nobility of the day -- and on the Americans, too. The tale, like many of Wilde\'s, is rich with allusion, but ends as sentimental romance...', 'Oscar Wilde', 6, 'Walker Books', 1920, 3.56, 126, 'Classics', '0828314292', 'English', 'assets/img/cover/c28.jpg', NULL, NULL, 'The Canterville Ghost is about an American family in the late 19th century that moves into Lord Canterville’s large and old home. However, the large house is haunted by Canterville’s ancestor, who tries to frighten the family away, or even to death! But this family isn’t to be scared away by a ghost, and is even intrigued by the historical mysteries it still carries.', 'No'),
(29, 'The Happy Prince', 'More than a hundred years ago, Oscar Wilde created this moving story for his children. Now shimmering illustrations, as bejeweled and golden as the Prince himself, give glowing life to the many dimensions of his tale. His story of friendship, love, and a willingness to part with one\'s own riches may be more important today than ever before. Full color.', 'Oscar Wilde', 6, 'Dutton Books', 1920, 4.23, 32, 'Classics', '0500651116', 'English', 'assets/img/cover/c29.jpg', NULL, NULL, 'This book is about the friendship between a swallow and a statue of a Happy Prince. The Happy Prince truly was just that- happy- in life because he lead a sheltered existence. \"My courtiers called me the Happy Prince, and happy indeed I was, if pleasure be happiness.\" This distinction foreshadows the story\'s intent to outline for us a deeper meaning in happiness. In life, the Prince was shielded from all misery. He passed, and was immortalized in the statue, which looked down upon the city.', 'Yes'),
(30, 'Harry Potter and the Chamber of Secrets', 'Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.\r\n\r\nAnd strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possible be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!', 'J.K. Rowling', 4, 'Arthur A. Levine Books', 1998, 4.43, 341, 'Fantasy', '1338716530', 'English', 'assets/img/cover/c30.jpg', NULL, NULL, 'It is the second book in J.K Rowling\'s fantastic book series Harry Potter. 12 year old Harry has just come back from Hogwarts School of Witchcraft and Wizardry to spend a dreadful summer at Number 4 Privit Drive. Little does he know his summer is about to get worse. Uncle Vernon is expecting to get one of the best deals of his life during a visit from the Masons. Unfortunately it doesn\'t go as planned when a house elf shows up in Harrys bedroom with an ominous message. The elf proceeds to try to get Harry expelled from Hogwarts by dropping a pudding on Mrs. Masons head. Uncle Vernon puts bars on Harrys window to stop him form getting out. Harry is in despair when the Ron (his best friend), Fred, and George(Ron\'s twin brothers) Weasley save him from the clutches of his aunt an uncle and he spend the restof the summer with them.', 'Yes'),
(31, 'Harry Potter and the Half-Blood Prince', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.\r\n\r\nAnd yet . . .\r\n\r\nAs in all wars, life goes on. The Weasley twins expand their business. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are never straightforward, through Harry receives some extraordinary help from the mysterious Half-Blood Prince.\r\n\r\nSo it\'s the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complete story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability.', 'J.K. Rowling', 4, 'Scholastic Press', 2005, 4.57, 652, 'Fantasy', '1526618222', 'English', 'assets/img/cover/c31.jpg', NULL, NULL, 'In this book, Harry Potter learns a lot about Lord Voldemort\'s past, and Harry Potter prepares for the final battle against his nemesis with the help of Headmaster Dumbledore. But in that time, Voldemort returns to power, and makes a plan to destroy Harry. So, Harry Potter tries to destroy Voldemort first, but for that, Harry must collect all parts of his soul. Voldemort had split his soul into pieces, so that he would never be totally destroyed, and now Harry has to destroy all the pieces, so Harry sets out with Dumbledore to find the Horcruxes.\r\n', 'Yes'),
(32, 'Hamlet', 'Among Shakespeare\'s plays, \"Hamlet\" is considered by many his masterpiece. Among actors, the role of Hamlet, Prince of Denmark, is considered the jewel in the crown of a triumphant theatrical career. Now Kenneth Branagh plays the leading role and co-directs a brillant ensemble performance. Three generations of legendary leading actors, many of whom first assembled for the Oscar-winning film \"Henry V\", gather here to perform the rarely heard complete version of the play. This clear, subtly nuanced, stunning dramatization, presented by The Renaissance Theatre Company in association with \"Bbc\" Broadcasting, features such luminaries as Sir John Gielgud, Derek Jacobi, Emma Thompson and Christopher Ravenscroft. It combines a full cast with stirring music and sound effects to bring this magnificent Shakespearen classic vividly to life. Revealing new riches with each listening, this production of \"Hamlet\" is an invaluable aid for students, teachers and all true lovers of Shakespeare - a recording to be treasured for decades to come.', 'William Shakespeare', 5, 'Cambridge University Press', 1920, 4.03, 289, 'Classics', '1774379759', 'English', 'assets/img/cover/c32.jpg', NULL, NULL, '\"Hamlet\" is a representative work in Shakespeare\'s tragedy, which was created in 1602. The ideological content has reached an unprecedented depth and breadth, and profoundly reveals the evil and essential characteristics of the society at the end of feudalism. ', 'Yes'),
(33, 'Macbeth', 'One night on the heath, the brave and respected general Macbeth encounters three witches who foretell that he will become king of Scotland. At first sceptical, he’s urged on by the ruthless, single-minded ambitions of Lady Macbeth, who suffers none of her husband’s doubt. But seeing the prophecy through to the bloody end leads them both spiralling into paranoia, tyranny, madness, and murder.\r\n\r\nThis shocking tragedy - a violent caution to those seeking power for its own sake - is, to this day, one of Shakespeare’s most popular and influential masterpieces.', 'William Shakespeare', 5, 'Simon & Schuster', 1920, 3.91, 249, 'Classics', '0743477103', 'English', 'assets/img/cover/c33.jpg', NULL, NULL, 'Macbeth is the story of how a little push for greed can send an aspiring, ambitious man on a disastrous and deadly fate. \r\n\r\n', 'Yes'),
(34, 'The Tempest', 'The Tempest is a play about magic, betrayal, love and forgiveness. It is set on an island somewhere near Italy where Prospero, the one-time Duke of Milan, and his beautiful daughter, Miranda, live with a sprite called Ariel and a strange wildman called Caliban. Prospero is a powerful magician who creates a storm, or tempest, that sets the scene for the play. In the events that follow we see a plot to murder the King of Naples, a drunken scheme to kill Prospero and a romance between Miranda and the King’s son, Ferdinand. In the end everyone is forgiven and they all set sail for home.', 'William Shakespeare', 5, 'Washington Square Press', 1920, 3.82, 218, 'Classics', '0743482832', 'English', 'assets/img/cover/c34.jpg', NULL, NULL, 'The story of The Tempest was actually a pleasant surprise. The story is about Prospero, a man looking for revenge against the one person who took his Dukedom away from him, his brother Antonio. At the beginning, the story moves a bit slow and can be a bit boring. Although, it does not take too long for Shakespeare to interest the reader with the plot of the novel. I did not find the story to be predictable, which is what made it so interesting! A theme that the story revolves around was Compassion VS Cruelty, making The Tempest very interesting and intriguing. The language of Shakespeare may be difficult to understand, but is not too difficult. Although, it would be useful to choose a version of The Tempest that has annotations/footnotes as there are various terms and mythological references that some people may not understand or know.', 'No'),
(35, 'A Midsummer Night’s Dream', 'Shakespeare\'s intertwined love polygons begin to get complicated from the start--Demetrius and Lysander both want Hermia but she only has eyes for Lysander. Bad news is, Hermia\'s father wants Demetrius for a son-in-law. On the outside is Helena, whose unreturned love burns hot for Demetrius. Hermia and Lysander plan to flee from the city under cover of darkness but are pursued by an enraged Demetrius (who is himself pursued by an enraptured Helena). In the forest, unbeknownst to the mortals, Oberon and Titania (King and Queen of the faeries) are having a spat over a servant boy. The plot twists up when Oberon\'s head mischief-maker, Puck, runs loose with a flower which causes people to fall in love with the first thing they see upon waking. Throw in a group of labourers preparing a play for the Duke\'s wedding (one of whom is given a donkey\'s head and Titania for a lover by Puck) and the complications become fantastically funny.', 'William Shakespeare', 5, 'Simon & Schuster ', 1921, 3.95, 240, 'Classics', '0743477545', 'English', 'assets/img/cover/c35.jpg', NULL, NULL, 'A Midsummer Night’s Dream has always been a great favourite of mine, ever since my school days. I was introduced to it at school when I was about 11 or 12. I’ve seen many productions of it. It’s the first play I edited, for the New Penguin Shakespeare, in 1967. I very much enjoyed writing about it then. It’s a play about imagination, about Shakespeare’s own heart, in many ways. The Mechanicals’ scenes, as they’re called, in which Shakespeare portrays amateur actors putting on the play of Pyramus and Thisbe, actually tell us an awful lot about Shakespeare’s attitude towards the theatre and the acting profession. They’re also wonderfully playable.It’s a play that appeals very much to young people. I’m speaking now from the Shakespeare Birthplace Trust at Stratford-Upon-Avon and we have what’s called ‘Shakespeare Week,’ when we engage with over 10,000 primary schools. The Royal Shakespeare Company put on a production of A Midsummer Night’s Dream which uses amateur actors, including schoolchildren.', 'Yes'),
(36, 'Catching Fire', 'Against all odds, Katniss Everdeen has won the Hunger Games. She and fellow District 12 tribute Peeta Mellark are miraculously still alive. Katniss should be relieved, happy even. After all, she has returned to her family and her longtime friend, Gale. Yet nothing is the way Katniss wishes it to be. Gale holds her at an icy distance. Peeta has turned his back on her completely. And there are whispers of a rebellion against the Capitol—a rebellion that Katniss and Peeta may have helped create.\r\n\r\nMuch to her shock, Katniss has fueled an unrest that she\'s afraid she cannot stop. And what scares her even more is that she\'s not entirely convinced she should try. As time draws near for Katniss and Peeta to visit the districts on the Capitol\'s cruel Victory Tour, the stakes are higher than ever. If they can\'t prove, without a shadow of a doubt, that they are lost in their love for each other, the consequences will be horrifying.\r\n\r\nIn Catching Fire, the second novel of the Hunger Games trilogy, Suzanne Collins continues the story of Katniss Everdeen, testing her more than ever before . . . and surprising readers at every turn.', 'Suzanne Collins', 3, 'Scholastic Press', 2009, 4.33, 391, 'Dystopian', '0545586178', 'English', 'assets/img/cover/c36.jpg', NULL, NULL, 'Catching Fire is an excellent sequel to The Hunger Games that takes us deeper into the aftermath of surviving the games and the torturous nightmares of such a disturbing place that make the terror unforgettable. After pulling the berries stunt that miraculously managed to keep both her and Peeta Mellark alive at the end of the Hunger Games, Katniss now faces the threat of losing her loved ones when President Snow realises that some people have taken Katniss\'s survival as an act of defiance, and a signal to rebel against the controlling Capitol. To keep her family and friends alive, Katniss must attempt to convince the entirety of Panem that her berries trick was purely out of an insatiable fear of losing Peeta, the love of her life, not as defiance against the Capitol.', 'Yes'),
(37, 'The Ballad of Songbirds and Snakes', 'It is the morning of the reaping that will kick off the tenth annual Hunger Games. In the Capital, eighteen-year-old Coriolanus Snow is preparing for his one shot at glory as a mentor in the Games. The once-mighty house of Snow has fallen on hard times, its fate hanging on the slender chance that Coriolanus will be able to outcharm, outwit, and outmaneuver his fellow students to mentor the winning tribute.\r\n\r\nThe odds are against him. He\'s been given the humiliating assignment of mentoring the female tribute from District 12, the lowest of the low. Their fates are now completely intertwined -- every choice Coriolanus makes could lead to favor or failure, triumph or ruin. Inside the arena, it will be a fight to the death. Outside the arena, Coriolanus starts to feel for his doomed tribute... and must weigh his need to follow the rules against his desire to survive no matter what it takes.', 'Suzanne Collins', 3, 'Scholastic Press', 2020, 3.82, 439, 'Dystopian', '1743836813', 'English', 'assets/img/cover/c37.jpg', NULL, NULL, 'he latest fictional dystopia is also an old one. This week sees the publication of Suzanne Collins’s The Ballad of Songbirds and Snakes, a prequel to her wildly successful Hunger Games trilogy about a dystopian world in which children are forced to battle to the death on reality TV. The new book is billed as an origin story for Coriolanus Snow, the future president of Panem and the chief villain of the original trilogy. And it fulfills that function capably enough, although it fails to ever quite reach the adrenaline-pumping urgency of the first trilogy', 'Yes');
INSERT INTO `books` (`book_id`, `title`, `description`, `author`, `author_id`, `publisher`, `year`, `rating`, `total_pages`, `category`, `isbn`, `language`, `image_url`, `pdf_url`, `mp3_url`, `review`, `audio`) VALUES
(38, 'The Lightning Thief', 'Percy Jackson is a good kid, but he can\'t seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse - Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy\'s mom finds out, she knows it\'s time that he knew the truth about where he came from, and that he go to the one place he\'ll be safe. She sends Percy to Camp Half Blood, a summer camp for demigods (on Long Island), where he learns that the father he never knew is Poseidon, God of the Sea. Soon a mystery unfolds and together with his friends—one a satyr and the other the demigod daughter of Athena - Percy sets out on a quest across the United States to reach the gates of the Underworld (located in a recording studio in Hollywood) and prevent a catastrophic war between the gods.', 'Rick Riordan', 2, 'Hyperion Books', 2006, 4.27, 377, 'Fantasy', '0786838655\n', 'English', 'assets/img/cover/c38.jpg', NULL, NULL, 'Percy Jackson and the Lightning Thief is a terrific tale of friendship and heroism! It’s got humour, light history, adventure and action; the best part is that this isn’t the end there’s at least four/five more books to look forward to reading', 'Yes'),
(39, 'The Sea of Monsters', 'The heroic son of Poseidon makes an action-packed comeback in the second must-read installment of Rick Riordan\'s amazing young readers series. Starring Percy Jackson, a \"half blood\" whose mother is human and whose father is the God of the Sea, Riordan\'s series combines cliffhanger adventure and Greek mythology lessons that results in true page-turners that get better with each installment.\r\n\r\nIn this episode, The Sea of Monsters, Percy sets out to retrieve the Golden Fleece before his summer camp is destroyed, surpassing the first book\'s drama and setting the stage for more thrills to come.', 'Rick Riordan', 2, 'Hyperion Books', 2006, 4.24, 279, 'Fantasy', '142314550X', 'English', 'assets/img/cover/c39.jpg', NULL, NULL, 'it has a creative and suspenseful story line and attaching characters. we meet Percy Jackson, a hero destined to save the world but doesn’t know how to, Annabeth Chase, a wise and courageous demigod and Grover Underwood, a troubled satyr who just wants to have some fun.', 'Yes'),
(40, 'The Titan\'s Curse', 'It\'s not everyday you find yourself in combat with a half-lion, half-human.\r\n\r\nBut when you\'re the son of a Greek god, it happens. And now my friend Annabeth is missing, a goddess is in chains and only five half-blood heroes can join the quest to defeat the doomsday monster.\r\n\r\nOh, and guess what? The Oracle has predicted that not all of us will survive...', 'Rick Riordan', 2, 'Puffin Books', 2007, 4.34, 320, 'Fantasy', '1423101480', 'English', 'assets/img/cover/c40.jpg', NULL, NULL, 'The stirring of monsters has begun. Monsters not seen for thousands of years threaten to unleash death and destruction on an unprecedented scale and destroy Olympus, and it’s up to Percy Jackson and his friends Grover, Annabeth and Thalia to stop them, though Percy is embarrassed to have to depend on his mother to drive him to his battles. Percy, Annabeth and Thalia are demigods, Grover is a satyr and their quest is to find the missing Artemis and the monster she was hunting.', 'Yes'),
(42, 'The Stranger', 'Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed \"the nakedness of man faced with the absurd.', 'Albert Camus', 17, 'Vintage International', 1942, 4.02, 123, 'Classics', '0679720200', 'French', 'assets/img/cover/c42.jpg', NULL, NULL, 'i think from time to time. how deep a book. everyone\'s a little meursalt in the modern world.', 'Yes'),
(43, 'The Plague', 'A gripping tale of human unrelieved horror, of survival and resilience, and of the ways in which humankind confronts death, The Plague is at once a masterfully crafted novel, eloquently understated and epic in scope, and a parable of ageless moral resonance, profoundly relevant to our times. In Oran, a coastal town in North Africa, the plague begins as a series of portents, unheeded by the people. It gradually becomes an omnipresent reality, obliterating all traces of the past and driving its victims to almost unearthly extremes of suffering, madness, and compassion.', 'Albert Camus', 17, 'Vintage International', 1947, 4.01, 308, 'Fiction', '0679720219', 'French', 'assets/img/cover/c43.jpg', NULL, NULL, 'However, it is a modern masterpiece of allegory, symbolism and imagery. The surface story is about plague in the early 1940s visiting the Algerian coastal city of Oran. While Camus tells a complete tale of disease, fear, despair, compassion and selfless heroism; the story of lasting significance is told between the lines with insightful observations and thought provoking dissertations on philosophy and theology.', 'Yes'),
(44, 'The Fall', 'Jean-Baptiste Clamence, a successful Parisian barrister, has come to recognize the deep-seated hypocrisy of his existence. His epigrammatic and, above all, discomforting monologue gradually saps, then undermines, the reader\'s own complacency.', 'Albert Camus', 17, 'Vintage International', 1956, 4.01, 147, 'Fiction', '0679720227', 'French', 'assets/img/cover/c44.jpg', NULL, NULL, 'The Fall is a philosophical novel by Albert Camus. First published in 1956, it is his last complete work of fiction.\r\n\r\nSet in Amsterdam, The Fall consists of a series of dramatic monologues by the self-proclaimed \"judge-penitent\" Jean-Baptiste Clamence, as he reflects upon his life to a stranger.\r\n\r\nIn what amounts to a confession, Clamence tells of his success as a wealthy Parisian defense lawyer who was highly respected by his colleagues; his crisis, and his ultimate \"fall\" from grace, was meant to invoke, in secular terms, The Fall of Man in the Garden of Eden.\r\n\r\nThe Fall explores themes of innocence, imprisonment, non-existence, and truth. In a eulogy to Albert Camus, existentialist philosopher Jean-Paul Sartre described the novel as \"perhaps the most beautiful and the least understood\" of Camus\' books.', 'No'),
(45, 'One Hundred Years of Solitude', 'The brilliant, bestselling, landmark novel that tells the story of the Buendia family, and chronicles the irreconcilable conflict between the desire for solitude and the need for love—in rich, imaginative prose that has come to define an entire genre known as \"magical realism.', 'Gabriel Garcia Marquez', 18, 'Harper Perennial', 1967, 4.09, 417, 'Classics', '0679444653', 'Spanish', 'assets/img/cover/c45.jpg', NULL, NULL, 'Well i finally completed \"One Hundred Years of Solitude\" , after 4 long years of delaying it. I had picked up the book many times before, but realised that i needed enough time to njoy and feel the magical journey the book was taking me through. With all the names similar and repeated generation after generation i really needed to njoy and allow the book to take me through the fantastic tale of magic, fantasy and reality. And from there on all i had to do was allow the book to lead me through the wonderfully woven tale of the Buendia generation.. and realised that i had already reached the enchanting and mystical magical end..... Fortunate to have read it... you really need to njoy and get immersed in the journey and\r\nrealise the magical experience.....Words are hard to describe the way the book ended..i read and re-read the end again and again and could only wonder and marvel at how beautifully and magically it ended...', 'Yes'),
(46, 'Love in the Time of Cholera', 'In their youth, Florentino Ariza and Fermina Daza fall passionately in love. When Fermina eventually chooses to marry a wealthy, well-born doctor, Florentino is heartbroken, but he is a romantic. As he rises in his business career he whiles away the years in 622 affairs—yet he reserves his heart for Fermina. Her husband dies at last, and Florentino purposefully attends the funeral. Fifty years, nine months, and four days after he first declared his love for Fermina, he will do so again.', 'Gabriel Garcia Marquez', 18, 'Vintage International', 1985, 3.92, 348, 'Classics', '0307389731', 'Spanish', 'assets/img/cover/c46.jpg', NULL, NULL, 'It is not a Love Story, it is a satire in a way. Gabriel warns the reader not to fall in his trap. All the characters in the book saw what they wanted to see, for instance, Fermentina and her boy share no face time to speak of yet profess undying love. In the end at old age she knows nothing about him and his failings yet fall in love and live happily ever after in their old age...their aged yet shallow superficial make believe world. The true love in the story was in the beginning...the photographer and the island girl of his youth...she could never have him fully yet loved every part of him and he with her. There was no motives in thier love.....no kids, no marriage, money...nothing.', 'Yes'),
(47, 'Chronicle of a Death Foretold\r\n', 'A man returns to the town where a baffling murder took place twenty-seven years earlier, determined to get to the bottom of the story. Just hours after marrying the beautiful Angela Vicario, everyone agrees, Bayardo San Roman returned his bride in disgrace to her parents. Her distraught family forced her to name her first lover; and her twin brothers announced their intention to murder Santiago Nasar for dishonoring their sister.\r\n\r\nYet if everyone knew the murder was going to happen, why did no one intervene to try and stop it? The more that is learned, the less is understood, and as the story races to its inexplicable conclusion, an entire society--not just a pair of murderers—is put on trial.', 'Gabriel Garcia Marquez', 18, 'Vintage International', 1981, 3.97, 120, 'Classics', '9500726076', 'Spanish', 'assets/img/cover/c47.jpg', NULL, NULL, 'I used this book for Spanish learning and found a lot of language that was unfamiliar and likely to be seldom used. I also hated the story line and the ending. Of all the books I have read in my learning project this is the only one I hated.', 'No'),
(48, 'The Black Book', 'Galip is a lawyer living in Istanbul. His wife, the detective novel–loving Ruya, has disappeared. Could she have left him for her ex-husband or Celâl, a popular newspaper columnist? But Celâl, too, seems to have vanished. As Galip investigates, he finds himself assuming the enviable Celâl\'s identity, wearing his clothes, answering his phone calls, even writing his columns. Galip pursues every conceivable clue, but the nature of the mystery keeps changing, and when he receives a death threat, he begins to fear the worst.\r\n\r\nWith its cascade of beguiling stories about Istanbul, The Black Book is a brilliantly unconventional mystery, and a provocative meditation on identity. For Turkish literary readers it is the cherished cult novel in which Orhan Pamuk found his original voice, but it has largely been neglected by English-language readers. Now, in Maureen Freely’s beautiful new translation, they, too, may encounter all its riches. ', 'Orhan Pamuk', 19, 'Vintage International', 1990, 3.92, 446, 'Fiction', '1400078652', 'Turkish', 'assets/img/cover/c48.jpg', NULL, NULL, 'Read many years ago, this is one of the top three books by Pamuk which I love the most. The other two being My Name Is Red and Snow - obvious choices.\r\n\r\nNo one makes old and modern Turkey come alive on page like Pamuk.', 'Yes'),
(49, 'My Name Is Red', 'At once a fiendishly devious mystery, a beguiling love story, and a brilliant symposium on the power of art, My Name Is Red is a transporting tale set amid the splendor and religious intrigue of sixteenth-century Istanbul, from one of the most prominent contemporary Turkish writers.\r\n\r\nThe Sultan has commissioned a cadre of the most acclaimed artists in the land to create a great book celebrating the glories of his realm. Their task: to illuminate the work in the European style. But because figurative art can be deemed an affront to Islam, this commission is a dangerous proposition indeed. The ruling elite therefore mustn’t know the full scope or nature of the project, and panic erupts when one of the chosen miniaturists disappears. The only clue to the mystery–or crime? –lies in the half-finished illuminations themselves. Part fantasy and part philosophical puzzle, My Name is Red is a kaleidoscopic journey to the intersection of art, religion, love, sex and power.', 'Orhan Pamuk', 19, 'Vintage International', 1998, 3.86, 417, 'Fiction', '0375706852', 'Turkish', 'assets/img/cover/c49.jpg', NULL, NULL, 'Generally, when a book starts out with a chapter entitled \"I Am A Corpse,\" you know it\'s going to be pretty good.\r\n\r\nThe novel is set up so that each chapter introduces a different narrator, including (but not limited to), Black, Black\'s uncle, Shekure, a dog, a horse, the murderer and various artists in the workshop. This type of structure for a mystery novel isn\'t new--Wilkie Collins, for example, employed it several times, most notably in The Moonstone--and it is an effective way to structure a story so as to hide the whodunit. Each character only tells as much as he, she or it knows and in Pamuk\'s novel even the murderer hides his or her identity.', 'Yes'),
(50, 'The Museum of Innocence', 'It is 1975, a perfect spring in Istanbul. Kemal, scion of one of the city’s wealthiest families, is about to become engaged to Sibel, daughter of another prominent family, when he encounters Füsun, a beautiful shopgirl and a distant relation. Once the long-lost cousins violate the code of virginity, a rift begins to open between Kemal and the world of the Westernized Istanbul bourgeosie—a world, as he lovingly describes it, with opulent parties and clubs, society gossip, restaurant rituals, picnics, and mansions on the Bosphorus, infused with the melancholy of decay—until finally he breaks off his engagement to Sibel. But his resolve comes too late.\r\n\r\nFor eight years Kemal will find excuses to visit another Istanbul, that of the impoverished backstreets where Füsun, her heart now hardened, lives with her parents, and where Kemal discovers the consolations of middle-class life at a dinner table in front of the television. His obsessive love will also take him to the demimonde of Istanbul film circles (where he promises to make Füsun a star), a scene of seedy bars, run-down cheap hotels, and small men with big dreams doomed to bitter failure. In his feckless pursuit, Kemal becomes a compulsive collector of objects that chronicle his lovelorn progress and his afflicted heart’s reactions: anger and impatience, remorse and humiliation, deluded hopes of recovery, and daydreams that transform Istanbul into a cityscape of signs and specters of his beloved, from whom now he can extract only meaningful glances and stolen kisses in cars, movie houses, and shadowy corners of parks. A last change to realize his dream will come to an awful end before Kemal discovers that all he finally can possess, certainly and eternally, is the museum he has created of his collection, this map of a society’s manners and mores, and of one man’s broken heart.\r\n\r\nA stirring exploration of the nature of romantic attachment and of the mysterious allure of collecting, The Museum of Innocence also plumbs the depths of an Istanbul half Western and half traditional—its emergent modernity, its vast cultural history. This is Orhan Pamuk’s greatest achievement.', 'Orhan Pamuk', 19, 'Knopf', 2008, 3.76, 536, 'Fiction', '0307386244', 'Turkish', 'assets/img/cover/c50.jpg', NULL, NULL, 'I think this will be a short review because i don\'t want to give too much away. This is probably one of the more unique books i\'ve ever read, done completely unpretentiously. most of the time i was reading it, i was thoroughly swept up in its melancholy atmosphere, but as the story began to resolve toward the very end, the tone lightened and i happily noted Orhan Pamuk\'s sense of humor and ability to make fun of himself. at least that is how i processed certain things at the end of the book.', 'Yes'),
(51, 'The Very Hungry Caterpillar', 'THE all-time classic story, from generation to generation, sold somewhere in the world every 30 seconds! Have you shared it with a child or grandchild in your life?\r\n\r\nOne sunny Sunday, the caterpillar was hatched out of a tiny egg. He was very hungry. On Monday, he ate through one apple; on Tuesday, he ate through three plums--and still he was hungry. When full at last, he made a cocoon around himself and went to sleep, to wake up a few weeks later wonderfully transformed into a butterfly!\r\n\r\nThe brilliantly innovative Eric Carle has dramatized the story of one of Nature\'s commonest yet loveliest marvels, the metamorphosis of the butterfly. This audiobook will delight as well as instruct the very youngest listener.', 'Eric Carle', 20, 'Puffin Books', 1969, 4.29, 26, 'Childrens', '0399208534', 'English', 'assets/img/cover/c51.png', NULL, NULL, 'Eric Carle\'s books have a special place in my heart. The way he creates his illustrations makes them so colorful and appealing to all.\r\n\r\nThe Very Hungry Caterpillar is one of our favorite books by him, but we enjoy them all equally. Brown Bear, Brown Bear, What Do You See?, The Grouchy Ladybug, The Very Busy Spider, The Very Quiet Cricket, and Dream Snow are just a few of our most cherished Eric Carle books.\r\n\r\nWhen you witness a toddler who can\'t read, recite all the words to these stories, you know just how much they love them too!', 'Yes'),
(52, 'The Cat in the Hat', 'This all-new rhymed bilingual edition of The Cat in the Hat is the perfect introduction for Spanish-speaking children to the wonderful world of Dr. Seuss. Now in a larger size trim to accommodate the English and the Spanish text, the new translation was written by Puerto Rican poet and children\'s book author Georgina Lázaro, and by Teresa Mlawer--one of the most respected figures in Spanish publishing. This new rhymed translation retains the fun of the original text, so that both Spanish-speakers and English-speakers can enjoy reading Dr. Seuss story in two languages.', 'Dr. Seuss', 21, 'Random House', 1985, 4.16, 61, 'Childrens', '000794716X', 'English', 'assets/img/cover/c52.jpg', NULL, NULL, 'I like that at the end of this book, when the mother comes home and the text reads:\r\n\r\nShould we tell her about it?\r\nNow, what SHOULD we do?\r\nWell...\r\nWhat would YOU do\r\nIf your mother asked YOU?\r\n\r\nMy daughter always looks up at me and says: I would tell you.\r\n\r\nBut I don\'t believe her. I think it\'s quite possible that the Cat in the Hat has already been here, and she\'s just telling me what I want to hear.', 'Yes'),
(53, 'The Polar Express', 'Awarded the prestigious Caldecott Medal in 1986, The Polar Express has sold more than 7 million copies, become a classic holiday movie, and been translated into stage productions that take place across the United States during the holiday season.', 'Chris Van Allsburg', 22, 'Houghton Mifflin', 1985, 4.31, 32, 'Childrens', '0544580141', 'English', 'assets/img/cover/c53.jpg', NULL, NULL, 'This book is a tradition of mine to read every year during Christmas. This season wouldn\'t be complete without the Polar Express! This is the best Christmas book EVER! ', 'Yes'),
(54, 'Jumanji', 'The game under the tree looked like a hundred others Peters and Judy had at home. But they were bored and restless and, looking for something interesting to do, thought they\'d give Jumanji a try. Little did they know when they unfolded its ordinary-looking playing board that they were about to be plunged into the most exciting and bizare adventure of their lives.\r\nIn his second book for children, Chris Van Allsburg again explores the ever-shifting line between fantasy and reality with this story about a game that comes startingly to life.\r\nHis marvelous drawings beautifully convey a mix of the everyday and the extraordinary, as a quiet house is taken over by an exotic jungle.', 'Chris Van Allsburg', 22, 'Houghton Mifflin', 1981, 4.03, 32, 'Childrens', '2211213413', 'English', 'assets/img/cover/c54.jpg', NULL, NULL, 'What an entertaining story! I first read this as a child, then I watched the movie with Robin Williams and fell in love all over again. But it was in my sophomore year at college when I was taking a course on \"Reading in the Elementary School,\" and had to pull together a portfolio of books, that I chose this Caldecott medal winner. It\'s very creative and helps teach so many different lessons to children. A must treasure for all children with a great imagination or those who need one! Yes.', 'Yes'),
(55, 'Charlie and the Chocolate Factory', 'Charlie Bucket\'s wonderful adventure begins when he finds one of Mr. Willy Wonka\'s precious Golden Tickets and wins a whole day inside the mysterious chocolate factory. Little does he know the surprises that are in store for him!', 'Roald Dahl', 23, 'Puffin Books', 1964, 4.14, 176, 'Childrens', '0142410314', 'English', 'assets/img/cover/c55.jpg', NULL, NULL, 'Tonight I just finished reading Charlie and the Chocolate factory with my son. This is the first chapter book I\'ve read all the way through with him. And it was a ton of fun.\r\n\r\nFirst off, I\'ll admit that I love the movie. I grew up with it. (I\'m talking about the Gene Wilder version, of course.)I\'ll even admit to liking the movie better than the book. Which is something that doesn\'t happen very often with me.\r\n\r\nThat said, the book is really, really good. It held my four-year old\'s attention. It\'s silly, and it\'s fun.', 'Yes');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `authors`
--
ALTER TABLE `authors`
  ADD PRIMARY KEY (`author_id`);

--
-- Tablo için indeksler `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`book_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `authors`
--
ALTER TABLE `authors`
  MODIFY `author_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- Tablo için AUTO_INCREMENT değeri `books`
--
ALTER TABLE `books`
  MODIFY `book_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
